apiVersion: v1
kind: Service
metadata:
  name: node-k8s-service
spec:
  type: NodePort
  selector:
    app: node-k8s-app
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # This will be accessible at http://localhost:30080
