name: Build and Deploy to Docker Hub

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/node-k8s-app:${{ github.sha }} .

    - name: Push Docker image
      run: docker push ${{ secrets.DOCKER_USERNAME }}/node-k8s-app:${{ github.sha }}

    - name: Update deployment.yaml with new image tag
      run: |
        sed -i "s|image: .*|image: ${{ secrets.DOCKER_USERNAME }}/node-k8s-app:${{ github.sha }}|" kubernetes/deployment.yaml

    - name: Commit and push updated deployment.yaml
  env:
    GH_TOKEN: ${{ secrets.GH_PAT }}
  run: |
    git config user.name "github-actions"
    git config user.email "actions@github.com"
    git add kubernetes/deployment.yaml
    git commit -m "Update image tag to ${{ github.sha }}" || echo "No changes to commit"
    git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/${{ github.repository }}
    git push